### ISSUE TITLE
Important

### ISSUE THREAD

**Issue by ghost** [AllPlatform/Termux-RaspbianOS#2]
Sorry , akira Yuki , this is not any issue 
 I am working on termux . I got success to run xfce . My aim is to run exagear on termux which is able to run 3d games. And I wants to add open gl es to it. Can you give me your gmail id because I wants to send you some work .

**Comment by SamarJi** [comment]
I installed xfce and lxde on termux (ubuntu) , it took 5gb memory. And it perfectly worked on vnc

**Comment by SamarJi** [comment]
See this screenshot
![IMG-20200611-WA0007](https://user-images.githubusercontent.com/65938569/84484092-e6d60600-acb7-11ea-96f4-281ed36a5c3e.jpg)
![IMG-20200611-WA0013](https://user-images.githubusercontent.com/65938569/84484111-ee95aa80-acb7-11ea-8a70-fe3a33de2d6a.jpg)

![IMG-20200611-WA0012](https://user-images.githubusercontent.com/65938569/84484116-f05f6e00-acb7-11ea-8619-4fa92707ba14.jpg)
How's my work, I the enough resolution to make it readable without zooming.

**Comment by SamarJi** [comment]
At next time , the resolution changed to default while running exagear.

**Comment by SamarJi** [comment]
The OS installed from anlinux is not good , it have root as primary user , and no SUDO

**Comment by ghost** [comment]
,

**Comment by mininxd** [comment]
> Sorry , akira Yuki , this is not any issue I am working on termux . I got success to run xfce . My aim is to run exagear on termux which is able to run 3d games. And I wants to add open gl es to it. Can you give me your gmail id because I wants to send you some work .

unfortunely, termux doesn't have hardware acceleration 😔
